small fixes

diff --git a/.github/workflows/deploy_to_aws.yml b/.github/workflows/deploy_to_aws.yml
--- a/.github/workflows/deploy_to_aws.yml
+++ b/.github/workflows/deploy_to_aws.yml
@@ -173,6 +173,10 @@ jobs:
           for id in $(aws cloudfront list-distributions --query "DistributionList.Items[*].Id" --output text); do
               domains=$(aws cloudfront get-distribution-config --id $id --query "DistributionConfig.Aliases.Items" --output text)
               if [[ "$domains" == "$CLOUDFRONT_DOMAIN" ]]; then
+                  if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
+                      echo "Error: Multiple CloudFront distributions found for domain: $CLOUDFRONT_DOMAIN"
+                      exit 1
+                  fi
                   echo "Found Distribution ID: $id for Domain: $CLOUDFRONT_DOMAIN"
                   CLOUDFRONT_DISTRIBUTION_ID=$id
               fi
